<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SharpClaw.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
    <PackageReference Include="Supprocom.Secrets" />
    <PackageReference Include="System.Security.Cryptography.Xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SharpClaw.Contracts" />
    <PackageReference Include="SharpClaw.Core" />
    <PackageReference Include="SharpClaw.Gateway.Contracts" />
    <ProjectReference Include="..\SharpClaw.Shared\SharpClaw.Shared.csproj" />
  </ItemGroup>

</Project>
