using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using SharpClaw.Build.GeneratedCodeSuppressions;

namespace SharpClaw.Tests.Architecture;

[SuppressMessage("Performance", "CA1812",
    Justification = "NUnit discovers and constructs this fixture through reflection.")]
[TestFixture]
internal sealed class GeneratedCodeSuppressionTests
{
    private const string UnoGeneratorPath =
        "Generated/Uno.Extensions.Core.Generators/Uno.Extensions.Core.Generators.KeyEqualityGenerator/";
    private const string CoverageHint = "SharpClaw.Services.ClientActionCoverageEntry.cs";
    private const string InstalledHint = "SharpClaw.Services.InstalledModuleIdentity.cs";
    private const string ProviderHint = "SharpClaw.Client.Uno.__KeyEqualityProvider.cs";
    private const string GatewayGeneratedPath =
        "Generated/Microsoft.AspNetCore.OpenApi.SourceGenerators/" +
        "Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator/" +
        "OpenApiXmlCommentSupport.generated.cs";
    private const string GeneratedNullableSource =
        "// <auto-generated/>\npublic sealed class Sample { public string? Value { get; set; } }\n";
    private const string GeneratedPlainSource =
        "// <auto-generated/>\npublic sealed class Sample { }\n";
    private static readonly PortableExecutableReference CoreLibrary =
        MetadataReference.CreateFromFile(typeof(object).Assembly.Location);

    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + CoverageHint)]
    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + InstalledHint)]
    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + ProviderHint)]
    [TestCase("SharpClaw.Client.Uno", "Generated\\Uno.Extensions.Core.Generators\\Uno.Extensions.Core.Generators.KeyEqualityGenerator\\" + CoverageHint)]
    [TestCase("SharpClaw.Tests", UnoGeneratorPath + CoverageHint)]
    [TestCase("SharpClaw.Client.Uno.Other", UnoGeneratorPath + CoverageHint)]
    [TestCase("SharpClaw.Client.Uno", "src/Services/" + CoverageHint)]
    [TestCase("SharpClaw.Client.Uno", "Generated/Other.Generators/Uno.Extensions.Core.Generators.KeyEqualityGenerator/" + CoverageHint)]
    [TestCase("SharpClaw.Client.Uno", "Generated/Uno.Extensions.Core.Generators/Other.KeyEqualityGenerator/" + CoverageHint)]
    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + "NewRecord.cs")]
    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + "nested/" + CoverageHint)]
    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + CoverageHint + ".bak")]
    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + "sharpclaw.services.ClientActionCoverageEntry.cs")]
    [TestCase("SharpClaw.Gateway", GatewayGeneratedPath)]
    [TestCase("SharpClaw.Tests", GatewayGeneratedPath)]
    public async Task CompilerNullableWarningsRemainActiveIncludingKnownUnoGeneratorOutputsAsync(
        string assemblyName,
        string sourcePath)
    {
        var compilation = CreateCompilation(assemblyName, GeneratedNullableSource, sourcePath);
        RequireWarning(compilation.GetDiagnostics(TestContext.CurrentContext.CancellationToken), "CS8669")
            .IsSuppressed.Should().BeFalse("the C# compiler must produce the warning before suppression");

        var diagnostics = await AnalyzeAsync(compilation, new GeneratedCodeDiagnosticSuppressor())
            .ConfigureAwait(false);

        RequireWarning(diagnostics, "CS8669").IsSuppressed.Should().BeFalse();
    }

    [TestCase("SharpClaw.Gateway", GatewayGeneratedPath, "HLQ005", true, true)]
    [TestCase("SharpClaw.Gateway", GatewayGeneratedPath, "HLQ012", true, true)]
    [TestCase("SharpClaw.Gateway", "Generated\\Microsoft.AspNetCore.OpenApi.SourceGenerators\\Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator\\OpenApiXmlCommentSupport.generated.cs", "HLQ005", true, true)]
    [TestCase("SharpClaw.Tests", GatewayGeneratedPath, "HLQ005", true, true)]
    [TestCase("SharpClaw.Tests", GatewayGeneratedPath, "HLQ012", true, true)]
    [TestCase("SharpClaw.Tests", "Generated\\Microsoft.AspNetCore.OpenApi.SourceGenerators\\Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator\\OpenApiXmlCommentSupport.generated.cs", "HLQ012", true, true)]
    [TestCase("SharpClaw.Gateway", GatewayGeneratedPath, "HLQ009", true, false)]
    [TestCase("SharpClaw.Tests", GatewayGeneratedPath, "HLQ009", true, false)]
    [TestCase("SharpClaw.Client.Uno", GatewayGeneratedPath, "HLQ005", true, false)]
    [TestCase("SharpClaw.Gateway.Other", GatewayGeneratedPath, "HLQ012", true, false)]
    [TestCase("SharpClaw.Tests.Other", GatewayGeneratedPath, "HLQ005", true, false)]
    [TestCase("SharpClaw.Gateway", "src/OpenApiXmlCommentSupport.generated.cs", "HLQ005", true, false)]
    [TestCase("SharpClaw.Gateway", "Generated/Other.SourceGenerators/Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator/OpenApiXmlCommentSupport.generated.cs", "HLQ005", true, false)]
    [TestCase("SharpClaw.Gateway", "Generated/Microsoft.AspNetCore.OpenApi.SourceGenerators/Other.XmlCommentGenerator/OpenApiXmlCommentSupport.generated.cs", "HLQ012", true, false)]
    [TestCase("SharpClaw.Gateway", "Generated/Microsoft.AspNetCore.OpenApi.SourceGenerators/Microsoft.AspNetCore.OpenApi.SourceGenerators.XmlCommentGenerator/Other.generated.cs", "HLQ005", true, false)]
    [TestCase("SharpClaw.Gateway", GatewayGeneratedPath + ".bak", "HLQ012", true, false)]
    [TestCase("SharpClaw.Gateway", GatewayGeneratedPath, "HLQ005", false, false)]
    [TestCase("SharpClaw.Gateway", GatewayGeneratedPath, "HLQ012", false, false)]
    [TestCase("SharpClaw.Tests", GatewayGeneratedPath, "HLQ005", false, false)]
    [TestCase("SharpClaw.Tests", GatewayGeneratedPath, "HLQ012", false, false)]
    [TestCase("SharpClaw.Gateway", UnoGeneratorPath + CoverageHint, "HLQ005", true, false)]
    [TestCase("SharpClaw.Client.Uno", UnoGeneratorPath + CoverageHint, "HLQ012", true, false)]
    public async Task AnalyzerWarningRequiresAnOwnedCompilationAndExactGeneratedOutputAsync(
        string assemblyName,
        string sourcePath,
        string diagnosticId,
        bool generatedHeader,
        bool expectSuppressed)
    {
        var source = generatedHeader ? GeneratedPlainSource : "public sealed class Sample { }\n";
        var compilation = CreateCompilation(assemblyName, source, sourcePath);
        var warningAnalyzer = new ControlledGeneratedWarningAnalyzer(diagnosticId);
        var baseline = await AnalyzeAsync(compilation, warningAnalyzer).ConfigureAwait(false);
        RequireWarning(baseline, diagnosticId).IsSuppressed.Should().BeFalse();

        var diagnostics = await AnalyzeAsync(
            compilation,
            warningAnalyzer,
            new GeneratedCodeDiagnosticSuppressor()).ConfigureAwait(false);

        RequireWarning(diagnostics, diagnosticId).IsSuppressed.Should().Be(expectSuppressed);
    }

    [TestCase("public sealed class Sample { public const string Marker = \"<auto-generated\"; }\n")]
    [TestCase("public sealed class Sample { }\n// <auto-generated/>\n")]
    public async Task GeneratedMarkerOutsideTheLeadingCommentCannotSuppressAuthoredCodeAsync(string source)
    {
        var compilation = CreateCompilation("SharpClaw.Gateway", source, GatewayGeneratedPath);
        var warningAnalyzer = new ControlledGeneratedWarningAnalyzer("HLQ005");
        var baseline = await AnalyzeAsync(compilation, warningAnalyzer).ConfigureAwait(false);
        RequireWarning(baseline, "HLQ005").IsSuppressed.Should().BeFalse();

        var diagnostics = await AnalyzeAsync(
            compilation,
            warningAnalyzer,
            new GeneratedCodeDiagnosticSuppressor()).ConfigureAwait(false);

        RequireWarning(diagnostics, "HLQ005").IsSuppressed.Should().BeFalse();
    }

    [TestCase("SharpClaw.Gateway")]
    [TestCase("SharpClaw.Tests")]
    public async Task AcceptedGeneratedPathRetainsOtherCompilerNullableWarningsAsync(string assemblyName)
    {
        const string source =
            "// <auto-generated/>\n#nullable enable\n" +
            "public sealed class Sample { public int Length(string? value) => value.Length; }\n";
        var compilation = CreateCompilation(assemblyName, source, GatewayGeneratedPath);
        RequireWarning(compilation.GetDiagnostics(TestContext.CurrentContext.CancellationToken), "CS8602")
            .IsSuppressed.Should().BeFalse();

        var diagnostics = await AnalyzeAsync(compilation, new GeneratedCodeDiagnosticSuppressor())
            .ConfigureAwait(false);

        RequireWarning(diagnostics, "CS8602").IsSuppressed.Should().BeFalse();
    }

    private static CSharpCompilation CreateCompilation(string assemblyName, string source, string sourcePath)
    {
        var tree = CSharpSyntaxTree.ParseText(
            source,
            CSharpParseOptions.Default.WithLanguageVersion(LanguageVersion.Latest),
            sourcePath,
            cancellationToken: TestContext.CurrentContext.CancellationToken);
        return CSharpCompilation.Create(
            assemblyName,
            [tree],
            [CoreLibrary],
            new CSharpCompilationOptions(
                OutputKind.DynamicallyLinkedLibrary,
                nullableContextOptions: NullableContextOptions.Enable));
    }

    private static Task<ImmutableArray<Diagnostic>> AnalyzeAsync(
        CSharpCompilation compilation,
        params DiagnosticAnalyzer[] analyzers)
    {
        var options = new CompilationWithAnalyzersOptions(
            new AnalyzerOptions([]),
            onAnalyzerException: null,
            concurrentAnalysis: true,
            logAnalyzerExecutionTime: false,
            reportSuppressedDiagnostics: true);
        return compilation.WithAnalyzers([.. analyzers], options)
            .GetAllDiagnosticsAsync(TestContext.CurrentContext.CancellationToken);
    }

    private static Diagnostic RequireWarning(ImmutableArray<Diagnostic> diagnostics, string diagnosticId)
    {
        diagnostics.Should().NotContain(diagnostic =>
            string.Equals(diagnostic.Id, "AD0001", StringComparison.Ordinal)
                || diagnostic.Severity == DiagnosticSeverity.Error,
            "the integration fixture and suppressor must run without compilation or analyzer failures");
        return diagnostics.Where(diagnostic => string.Equals(diagnostic.Id, diagnosticId, StringComparison.Ordinal))
            .Should().ContainSingle().Which;
    }
}
